import {   
  MD3DarkTheme, 
  MD3LightTheme,
  adaptNavigationTheme,
} from 'react-native-paper';
import {
  DarkTheme as NavigationDarkTheme,
  DefaultTheme as NavigationDefaultTheme,
} from '@react-navigation/native';


export const theme = {
  "seed": "#F26312",
  "name": "material-theme",
  "description": "TYPE: CUSTOM",
  "baseline": false,
  "extendedColors": [],
  "coreColors": {
    "primary": "#F26312",
    "secondary": "#EAD20C",
    "tertiary": "#052B46",
    "neutral": "#021420"
  },
  "schemes": {
    "light": {
      "primary": "#a43e00",
      "onPrimary": "#ffffff",
      "primaryContainer": "#ffdbcd",
      "onPrimaryContainer": "#360f00",
      "primaryFixed": "#ffdbcd",
      "onPrimaryFixed": "#360f00",
      "primaryFixedDim": "#ffb596",
      "onPrimaryFixedVariant": "#7d2d00",
      "secondary": "#6b5f00",
      "onSecondary": "#ffffff",
      "secondaryContainer": "#fde42a",
      "onSecondaryContainer": "#201c00",
      "secondaryFixed": "#fde42a",
      "onSecondaryFixed": "#201c00",
      "secondaryFixedDim": "#dfc700",
      "onSecondaryFixedVariant": "#504700",
      "tertiary": "#00639c",
      "onTertiary": "#ffffff",
      "tertiaryContainer": "#cee5ff",
      "onTertiaryContainer": "#001d33",
      "tertiaryFixed": "#cee5ff",
      "onTertiaryFixed": "#001d33",
      "tertiaryFixedDim": "#98cbff",
      "onTertiaryFixedVariant": "#004a77",
      "error": "#ba1a1a",
      "errorContainer": "#ffdad6",
      "onError": "#ffffff",
      "onErrorContainer": "#410002",
      "background": "#fcfcff",
      "onBackground": "#191c1e",
      "outline": "#85736c",
      "inverseOnSurface": "#f0f0f3",
      "inverseSurface": "#2e3133",
      "inversePrimary": "#ffb596",
      "shadow": "#000000",
      "surfaceTint": "#a43e00",
      "outlineVariant": "#d8c2ba",
      "scrim": "#000000",
      "surface": "#f9f9fc",
      "onSurface": "#191c1e",
      "surfaceVariant": "#f5ded5",
      "onSurfaceVariant": "#53443e",
      "surfaceContainerHighest": "#e2e2e5",
      "surfaceContainerHigh": "#e7e8eb",
      "surfaceContainer": "#edeef0",
      "surfaceContainerLow": "#f3f3f6",
      "surfaceContainerLowest": "#ffffff",
      "surfaceDim": "#d9dadd",
      "surfaceBright": "#f9f9fc"
    },
    "dark": {
      "primary": "#ffb596",
      "onPrimary": "#581e00",
      "primaryContainer": "#7d2d00",
      "onPrimaryContainer": "#ffdbcd",
      "primaryFixed": "#ffdbcd",
      "onPrimaryFixed": "#360f00",
      "primaryFixedDim": "#ffb596",
      "onPrimaryFixedVariant": "#7d2d00",
      "secondary": "#dfc700",
      "onSecondary": "#373100",
      "secondaryContainer": "#504700",
      "onSecondaryContainer": "#fde42a",
      "secondaryFixed": "#fde42a",
      "onSecondaryFixed": "#201c00",
      "secondaryFixedDim": "#dfc700",
      "onSecondaryFixedVariant": "#504700",
      "tertiary": "#98cbff",
      "onTertiary": "#003354",
      "tertiaryContainer": "#004a77",
      "onTertiaryContainer": "#cee5ff",
      "tertiaryFixed": "#cee5ff",
      "onTertiaryFixed": "#001d33",
      "tertiaryFixedDim": "#98cbff",
      "onTertiaryFixedVariant": "#004a77",
      "error": "#ffb4ab",
      "errorContainer": "#93000a",
      "onError": "#690005",
      "onErrorContainer": "#ffdad6",
      "background": "#191c1e",
      "onBackground": "#e2e2e5",
      "outline": "#a08d85",
      "inverseOnSurface": "#191c1e",
      "inverseSurface": "#e2e2e5",
      "inversePrimary": "#a43e00",
      "shadow": "#000000",
      "surfaceTint": "#ffb596",
      "outlineVariant": "#53443e",
      "scrim": "#000000",
      "surface": "#111416",
      "onSurface": "#c5c6c9",
      "surfaceVariant": "#53443e",
      "onSurfaceVariant": "#d8c2ba",
      "surfaceContainerHighest": "#333537",
      "surfaceContainerHigh": "#282a2c",
      "surfaceContainer": "#1e2022",
      "surfaceContainerLow": "#191c1e",
      "surfaceContainerLowest": "#0c0e11",
      "surfaceDim": "#111416",
      "surfaceBright": "#37393c"
    },
    "androidLight": {
      "colorAccentPrimary": "#ffdbcd",
      "colorAccentPrimaryVariant": "#a43e00",
      "colorAccentSecondary": "#fde42a",
      "colorAccentSecondaryVariant": "#6b5f00",
      "colorAccentTertiary": "#cee5ff",
      "colorAccentTertiaryVariant": "#00639c",
      "textColorPrimary": "#191c1e",
      "textColorSecondary": "#53443e",
      "textColorTertiary": "#85736c",
      "textColorPrimaryInverse": "#f0f0f3",
      "textColorSecondaryInverse": "#c5c6c9",
      "textColorTertiaryInverse": "#8f9193",
      "colorBackground": "#f0f0f3",
      "colorBackgroundFloating": "#f9f9fc",
      "colorSurface": "#f9f9fc",
      "colorSurfaceVariant": "#e2e2e5",
      "colorSurfaceHighlight": "#ffffff",
      "surfaceHeader": "#e2e2e5",
      "underSurface": "#000000",
      "offState": "#2e3133",
      "accentSurface": "#ffede7",
      "textPrimaryOnAccent": "#191c1e",
      "textSecondaryOnAccent": "#53443e",
      "volumeBackground": "#393c3e",
      "scrim": "#c5c6c9"
    },
    "androidDark": {
      "colorAccentPrimary": "#ffdbcd",
      "colorAccentPrimaryVariant": "#ff8c58",
      "colorAccentSecondary": "#fde42a",
      "colorAccentSecondaryVariant": "#c0ac00",
      "colorAccentTertiary": "#cee5ff",
      "colorAccentTertiaryVariant": "#66b1f4",
      "textColorPrimary": "#f0f0f3",
      "textColorSecondary": "#d8c2ba",
      "textColorTertiary": "#a08d85",
      "textColorPrimaryInverse": "#191c1e",
      "textColorSecondaryInverse": "#454749",
      "textColorTertiaryInverse": "#75777a",
      "colorBackground": "#191c1e",
      "colorBackgroundFloating": "#191c1e",
      "colorSurface": "#2e3133",
      "colorSurfaceVariant": "#454749",
      "colorSurfaceHighlight": "#515355",
      "surfaceHeader": "#454749",
      "underSurface": "#000000",
      "offState": "#2e3133",
      "accentSurface": "#ffede7",
      "textPrimaryOnAccent": "#191c1e",
      "textSecondaryOnAccent": "#53443e",
      "volumeBackground": "#393c3e",
      "scrim": "#c5c6c9"
    }
  },
  "palettes": {
    "primary": [
      "#000000",
      null,
      null,
      null,
      "#200600",
      "#250800",
      "#290900",
      null,
      null,
      null,
      "#360f00",
      null,
      "#3d1200",
      null,
      null,
      null,
      null,
      "#4e1900",
      null,
      null,
      "#581e00",
      null,
      "#5f2100",
      null,
      "#672400",
      "#6a2500",
      null,
      null,
      null,
      null,
      "#7d2d00",
      null,
      null,
      null,
      null,
      "#903500",
      null,
      null,
      null,
      null,
      "#a43e00",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#cc4f00",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#f36413",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#ff8c58",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#ffb596",
      null,
      null,
      null,
      null,
      null,
      null,
      "#ffd0bd",
      null,
      null,
      "#ffdbcd",
      null,
      "#ffe2d7",
      null,
      "#ffe9e2",
      "#ffede7",
      "#fff1ec",
      null,
      "#fff8f6",
      "#fffbff",
      "#ffffff"
    ],
    "secondary": [
      "#000000",
      null,
      null,
      null,
      "#110e00",
      "#141100",
      "#171300",
      null,
      null,
      null,
      "#201c00",
      null,
      "#252000",
      null,
      null,
      null,
      null,
      "#302a00",
      null,
      null,
      "#373100",
      null,
      "#3c3500",
      null,
      "#413900",
      "#443c00",
      null,
      null,
      null,
      null,
      "#504700",
      null,
      null,
      null,
      null,
      "#5d5300",
      null,
      null,
      null,
      null,
      "#6b5f00",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#867800",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#a39100",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#c0ac00",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#dfc700",
      null,
      null,
      null,
      null,
      null,
      null,
      "#f4db1e",
      null,
      null,
      "#fde42a",
      null,
      "#ffea5d",
      null,
      "#ffef94",
      "#fff2ab",
      "#fff4c1",
      null,
      "#fff9ea",
      "#fffbff",
      "#ffffff"
    ],
    "tertiary": [
      "#000000",
      null,
      null,
      null,
      "#000f1e",
      "#001222",
      "#001526",
      null,
      null,
      null,
      "#001d33",
      null,
      "#002139",
      null,
      null,
      null,
      null,
      "#002c4a",
      null,
      null,
      "#003354",
      null,
      "#00375b",
      null,
      "#003c62",
      "#003e65",
      null,
      null,
      null,
      null,
      "#004a77",
      null,
      null,
      null,
      null,
      "#005689",
      null,
      null,
      null,
      null,
      "#00639c",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#257cbc",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#4896d7",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#66b1f4",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#98cbff",
      null,
      null,
      null,
      null,
      null,
      null,
      "#bfddff",
      null,
      null,
      "#cee5ff",
      null,
      "#d9eaff",
      null,
      "#e3efff",
      "#e8f2ff",
      "#edf4ff",
      null,
      "#f7f9ff",
      "#fcfcff",
      "#ffffff"
    ],
    "neutral": [
      "#000000",
      null,
      null,
      null,
      "#0c0e11",
      "#0f1113",
      "#111416",
      null,
      null,
      null,
      "#191c1e",
      null,
      "#1e2022",
      null,
      null,
      null,
      null,
      "#282a2c",
      null,
      null,
      "#2e3133",
      null,
      "#333537",
      null,
      "#37393c",
      "#393c3e",
      null,
      null,
      null,
      null,
      "#454749",
      null,
      null,
      null,
      null,
      "#515355",
      null,
      null,
      null,
      null,
      "#5d5e61",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#75777a",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#8f9193",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#aaabae",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#c5c6c9",
      null,
      null,
      null,
      null,
      null,
      null,
      "#d9dadd",
      null,
      null,
      "#e2e2e5",
      null,
      "#e7e8eb",
      null,
      "#edeef0",
      "#f0f0f3",
      "#f3f3f6",
      null,
      "#f9f9fc",
      "#fcfcff",
      "#ffffff"
    ],
    "neutralVariant": [
      "#000000",
      null,
      null,
      null,
      "#160c08",
      "#190e0a",
      "#1c110c",
      null,
      null,
      null,
      "#251914",
      null,
      "#291d18",
      null,
      null,
      null,
      null,
      "#342722",
      null,
      null,
      "#3b2d28",
      null,
      "#40322c",
      null,
      "#443630",
      "#473833",
      null,
      null,
      null,
      null,
      "#53443e",
      null,
      null,
      null,
      null,
      "#5f4f49",
      null,
      null,
      null,
      null,
      "#6b5b54",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#85736c",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#a08d85",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#bba79f",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#d8c2ba",
      null,
      null,
      null,
      null,
      null,
      null,
      "#ecd5cd",
      null,
      null,
      "#f5ded5",
      null,
      "#fae3db",
      null,
      "#ffe9e2",
      "#ffede7",
      "#fff1ec",
      null,
      "#fff8f6",
      "#fffbff",
      "#ffffff"
    ],
    "error": [
      "#000000",
      null,
      null,
      null,
      "#280001",
      "#2d0001",
      "#310001",
      null,
      null,
      null,
      "#410002",
      null,
      "#490002",
      null,
      null,
      null,
      null,
      "#5c0004",
      null,
      null,
      "#690005",
      null,
      "#710005",
      null,
      "#790006",
      "#7e0007",
      null,
      null,
      null,
      null,
      "#93000a",
      null,
      null,
      null,
      null,
      "#a80710",
      null,
      null,
      null,
      null,
      "#ba1a1a",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#de3730",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#ff5449",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#ff897d",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#ffb4ab",
      null,
      null,
      null,
      null,
      null,
      null,
      "#ffcfc9",
      null,
      null,
      "#ffdad6",
      null,
      "#ffe2de",
      null,
      "#ffe9e6",
      "#ffedea",
      "#fff0ee",
      null,
      "#fff8f7",
      "#fffbff",
      "#ffffff"
    ]
  },
  "styles": {
    "display": {
      "large": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Regular",
        "fontWeight": 400,
        "fontSize": 57,
        "lineHeight": 64,
        "letterSpacing": -0.25
      },
      "medium": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Regular",
        "fontWeight": 400,
        "fontSize": 45,
        "lineHeight": 52,
        "letterSpacing": 0
      },
      "small": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Regular",
        "fontWeight": 400,
        "fontSize": 36,
        "lineHeight": 44,
        "letterSpacing": 0
      }
    },
    "headline": {
      "large": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Regular",
        "fontWeight": 400,
        "fontSize": 32,
        "lineHeight": 40,
        "letterSpacing": 0
      },
      "medium": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Regular",
        "fontWeight": 400,
        "fontSize": 28,
        "lineHeight": 36,
        "letterSpacing": 0
      },
      "small": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Regular",
        "fontWeight": 400,
        "fontSize": 24,
        "lineHeight": 32,
        "letterSpacing": 0
      }
    },
    "body": {
      "large": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Regular",
        "fontWeight": 400,
        "fontSize": 16,
        "lineHeight": 24,
        "letterSpacing": 0.5
      },
      "medium": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Regular",
        "fontWeight": 400,
        "fontSize": 14,
        "lineHeight": 20,
        "letterSpacing": 0.25
      },
      "small": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Regular",
        "fontWeight": 400,
        "fontSize": 12,
        "lineHeight": 16,
        "letterSpacing": 0.4000000059604645
      }
    },
    "label": {
      "large": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Medium",
        "fontWeight": 500,
        "fontSize": 14,
        "lineHeight": 20,
        "letterSpacing": 0.10000000149011612
      },
      "medium": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Medium",
        "fontWeight": 500,
        "fontSize": 12,
        "lineHeight": 16,
        "letterSpacing": 0.5
      },
      "small": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Medium",
        "fontWeight": 500,
        "fontSize": 11,
        "lineHeight": 16,
        "letterSpacing": 0.5
      }
    },
    "title": {
      "large": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Regular",
        "fontWeight": 400,
        "fontSize": 22,
        "lineHeight": 28,
        "letterSpacing": 0
      },
      "medium": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Medium",
        "fontWeight": 500,
        "fontSize": 16,
        "lineHeight": 24,
        "letterSpacing": 0.15000000596046448
      },
      "small": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Medium",
        "fontWeight": 500,
        "fontSize": 14,
        "lineHeight": 20,
        "letterSpacing": 0.10000000149011612
      }
    }
  },
  "customColors": []
}
const { LightTheme, DarkTheme } = adaptNavigationTheme({
  reactNavigationLight: NavigationDefaultTheme,
  reactNavigationDark: NavigationDarkTheme,
});

export const CombinedDefaultTheme = {
  ...MD3LightTheme,
  ...LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    ...LightTheme.colors,
    ...theme.schemes.light,
  },
};

export const CombinedDarkTheme = {
  ...MD3DarkTheme,
  ...DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    ...DarkTheme.colors,
    ...theme.schemes.dark,
  },
};

const secondTheme = 
{
  "seed": "#F26312",
  "name": "material-theme",
  "description": "TYPE: CUSTOM",
  "baseline": false,
  "extendedColors": [],
  "coreColors": {
    "primary": "#F26312",
    "secondary": "#052B46",
    "tertiary": "#EAD20C",
    "neutral": "#021420"
  },
  "schemes": {
    "light": {
      "primary": "#a43e00",
      "onPrimary": "#ffffff",
      "primaryContainer": "#ffdbcd",
      "onPrimaryContainer": "#360f00",
      "primaryFixed": "#ffdbcd",
      "onPrimaryFixed": "#360f00",
      "primaryFixedDim": "#ffb596",
      "onPrimaryFixedVariant": "#7d2d00",
      "secondary": "#00639c",
      "onSecondary": "#ffffff",
      "secondaryContainer": "#cee5ff",
      "onSecondaryContainer": "#001d33",
      "secondaryFixed": "#cee5ff",
      "onSecondaryFixed": "#001d33",
      "secondaryFixedDim": "#98cbff",
      "onSecondaryFixedVariant": "#004a77",
      "tertiary": "#6b5f00",
      "onTertiary": "#ffffff",
      "tertiaryContainer": "#fde42a",
      "onTertiaryContainer": "#201c00",
      "tertiaryFixed": "#fde42a",
      "onTertiaryFixed": "#201c00",
      "tertiaryFixedDim": "#dfc700",
      "onTertiaryFixedVariant": "#504700",
      "error": "#ba1a1a",
      "errorContainer": "#ffdad6",
      "onError": "#ffffff",
      "onErrorContainer": "#410002",
      "background": "#fcfcff",
      "onBackground": "#191c1e",
      "outline": "#85736c",
      "inverseOnSurface": "#f0f0f3",
      "inverseSurface": "#2e3133",
      "inversePrimary": "#ffb596",
      "shadow": "#000000",
      "surfaceTint": "#a43e00",
      "outlineVariant": "#d8c2ba",
      "scrim": "#000000",
      "surface": "#f9f9fc",
      "onSurface": "#191c1e",
      "surfaceVariant": "#f5ded5",
      "onSurfaceVariant": "#53443e",
      "surfaceContainerHighest": "#e2e2e5",
      "surfaceContainerHigh": "#e7e8eb",
      "surfaceContainer": "#edeef0",
      "surfaceContainerLow": "#f3f3f6",
      "surfaceContainerLowest": "#ffffff",
      "surfaceDim": "#d9dadd",
      "surfaceBright": "#f9f9fc"
    },
    "dark": {
      "primary": "#ffb596",
      "onPrimary": "#581e00",
      "primaryContainer": "#7d2d00",
      "onPrimaryContainer": "#ffdbcd",
      "primaryFixed": "#ffdbcd",
      "onPrimaryFixed": "#360f00",
      "primaryFixedDim": "#ffb596",
      "onPrimaryFixedVariant": "#7d2d00",
      "secondary": "#98cbff",
      "onSecondary": "#003354",
      "secondaryContainer": "#004a77",
      "onSecondaryContainer": "#cee5ff",
      "secondaryFixed": "#cee5ff",
      "onSecondaryFixed": "#001d33",
      "secondaryFixedDim": "#98cbff",
      "onSecondaryFixedVariant": "#004a77",
      "tertiary": "#dfc700",
      "onTertiary": "#373100",
      "tertiaryContainer": "#504700",
      "onTertiaryContainer": "#fde42a",
      "tertiaryFixed": "#fde42a",
      "onTertiaryFixed": "#201c00",
      "tertiaryFixedDim": "#dfc700",
      "onTertiaryFixedVariant": "#504700",
      "error": "#ffb4ab",
      "errorContainer": "#93000a",
      "onError": "#690005",
      "onErrorContainer": "#ffdad6",
      "background": "#191c1e",
      "onBackground": "#e2e2e5",
      "outline": "#a08d85",
      "inverseOnSurface": "#191c1e",
      "inverseSurface": "#e2e2e5",
      "inversePrimary": "#a43e00",
      "shadow": "#000000",
      "surfaceTint": "#ffb596",
      "outlineVariant": "#53443e",
      "scrim": "#000000",
      "surface": "#111416",
      "onSurface": "#c5c6c9",
      "surfaceVariant": "#53443e",
      "onSurfaceVariant": "#d8c2ba",
      "surfaceContainerHighest": "#333537",
      "surfaceContainerHigh": "#282a2c",
      "surfaceContainer": "#1e2022",
      "surfaceContainerLow": "#191c1e",
      "surfaceContainerLowest": "#0c0e11",
      "surfaceDim": "#111416",
      "surfaceBright": "#37393c"
    },
    "androidLight": {
      "colorAccentPrimary": "#ffdbcd",
      "colorAccentPrimaryVariant": "#a43e00",
      "colorAccentSecondary": "#cee5ff",
      "colorAccentSecondaryVariant": "#00639c",
      "colorAccentTertiary": "#fde42a",
      "colorAccentTertiaryVariant": "#6b5f00",
      "textColorPrimary": "#191c1e",
      "textColorSecondary": "#53443e",
      "textColorTertiary": "#85736c",
      "textColorPrimaryInverse": "#f0f0f3",
      "textColorSecondaryInverse": "#c5c6c9",
      "textColorTertiaryInverse": "#8f9193",
      "colorBackground": "#f0f0f3",
      "colorBackgroundFloating": "#f9f9fc",
      "colorSurface": "#f9f9fc",
      "colorSurfaceVariant": "#e2e2e5",
      "colorSurfaceHighlight": "#ffffff",
      "surfaceHeader": "#e2e2e5",
      "underSurface": "#000000",
      "offState": "#2e3133",
      "accentSurface": "#ffede7",
      "textPrimaryOnAccent": "#191c1e",
      "textSecondaryOnAccent": "#53443e",
      "volumeBackground": "#393c3e",
      "scrim": "#c5c6c9"
    },
    "androidDark": {
      "colorAccentPrimary": "#ffdbcd",
      "colorAccentPrimaryVariant": "#ff8c58",
      "colorAccentSecondary": "#cee5ff",
      "colorAccentSecondaryVariant": "#66b1f4",
      "colorAccentTertiary": "#fde42a",
      "colorAccentTertiaryVariant": "#c0ac00",
      "textColorPrimary": "#f0f0f3",
      "textColorSecondary": "#d8c2ba",
      "textColorTertiary": "#a08d85",
      "textColorPrimaryInverse": "#191c1e",
      "textColorSecondaryInverse": "#454749",
      "textColorTertiaryInverse": "#75777a",
      "colorBackground": "#191c1e",
      "colorBackgroundFloating": "#191c1e",
      "colorSurface": "#2e3133",
      "colorSurfaceVariant": "#454749",
      "colorSurfaceHighlight": "#515355",
      "surfaceHeader": "#454749",
      "underSurface": "#000000",
      "offState": "#2e3133",
      "accentSurface": "#ffede7",
      "textPrimaryOnAccent": "#191c1e",
      "textSecondaryOnAccent": "#53443e",
      "volumeBackground": "#393c3e",
      "scrim": "#c5c6c9"
    }
  },
  "palettes": {
    "primary": [
      "#000000",
      null,
      null,
      null,
      "#200600",
      "#250800",
      "#290900",
      null,
      null,
      null,
      "#360f00",
      null,
      "#3d1200",
      null,
      null,
      null,
      null,
      "#4e1900",
      null,
      null,
      "#581e00",
      null,
      "#5f2100",
      null,
      "#672400",
      "#6a2500",
      null,
      null,
      null,
      null,
      "#7d2d00",
      null,
      null,
      null,
      null,
      "#903500",
      null,
      null,
      null,
      null,
      "#a43e00",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#cc4f00",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#f36413",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#ff8c58",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#ffb596",
      null,
      null,
      null,
      null,
      null,
      null,
      "#ffd0bd",
      null,
      null,
      "#ffdbcd",
      null,
      "#ffe2d7",
      null,
      "#ffe9e2",
      "#ffede7",
      "#fff1ec",
      null,
      "#fff8f6",
      "#fffbff",
      "#ffffff"
    ],
    "secondary": [
      "#000000",
      null,
      null,
      null,
      "#000f1e",
      "#001222",
      "#001526",
      null,
      null,
      null,
      "#001d33",
      null,
      "#002139",
      null,
      null,
      null,
      null,
      "#002c4a",
      null,
      null,
      "#003354",
      null,
      "#00375b",
      null,
      "#003c62",
      "#003e65",
      null,
      null,
      null,
      null,
      "#004a77",
      null,
      null,
      null,
      null,
      "#005689",
      null,
      null,
      null,
      null,
      "#00639c",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#257cbc",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#4896d7",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#66b1f4",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#98cbff",
      null,
      null,
      null,
      null,
      null,
      null,
      "#bfddff",
      null,
      null,
      "#cee5ff",
      null,
      "#d9eaff",
      null,
      "#e3efff",
      "#e8f2ff",
      "#edf4ff",
      null,
      "#f7f9ff",
      "#fcfcff",
      "#ffffff"
    ],
    "tertiary": [
      "#000000",
      null,
      null,
      null,
      "#110e00",
      "#141100",
      "#171300",
      null,
      null,
      null,
      "#201c00",
      null,
      "#252000",
      null,
      null,
      null,
      null,
      "#302a00",
      null,
      null,
      "#373100",
      null,
      "#3c3500",
      null,
      "#413900",
      "#443c00",
      null,
      null,
      null,
      null,
      "#504700",
      null,
      null,
      null,
      null,
      "#5d5300",
      null,
      null,
      null,
      null,
      "#6b5f00",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#867800",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#a39100",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#c0ac00",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#dfc700",
      null,
      null,
      null,
      null,
      null,
      null,
      "#f4db1e",
      null,
      null,
      "#fde42a",
      null,
      "#ffea5d",
      null,
      "#ffef94",
      "#fff2ab",
      "#fff4c1",
      null,
      "#fff9ea",
      "#fffbff",
      "#ffffff"
    ],
    "neutral": [
      "#000000",
      null,
      null,
      null,
      "#0c0e11",
      "#0f1113",
      "#111416",
      null,
      null,
      null,
      "#191c1e",
      null,
      "#1e2022",
      null,
      null,
      null,
      null,
      "#282a2c",
      null,
      null,
      "#2e3133",
      null,
      "#333537",
      null,
      "#37393c",
      "#393c3e",
      null,
      null,
      null,
      null,
      "#454749",
      null,
      null,
      null,
      null,
      "#515355",
      null,
      null,
      null,
      null,
      "#5d5e61",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#75777a",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#8f9193",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#aaabae",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#c5c6c9",
      null,
      null,
      null,
      null,
      null,
      null,
      "#d9dadd",
      null,
      null,
      "#e2e2e5",
      null,
      "#e7e8eb",
      null,
      "#edeef0",
      "#f0f0f3",
      "#f3f3f6",
      null,
      "#f9f9fc",
      "#fcfcff",
      "#ffffff"
    ],
    "neutralVariant": [
      "#000000",
      null,
      null,
      null,
      "#160c08",
      "#190e0a",
      "#1c110c",
      null,
      null,
      null,
      "#251914",
      null,
      "#291d18",
      null,
      null,
      null,
      null,
      "#342722",
      null,
      null,
      "#3b2d28",
      null,
      "#40322c",
      null,
      "#443630",
      "#473833",
      null,
      null,
      null,
      null,
      "#53443e",
      null,
      null,
      null,
      null,
      "#5f4f49",
      null,
      null,
      null,
      null,
      "#6b5b54",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#85736c",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#a08d85",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#bba79f",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#d8c2ba",
      null,
      null,
      null,
      null,
      null,
      null,
      "#ecd5cd",
      null,
      null,
      "#f5ded5",
      null,
      "#fae3db",
      null,
      "#ffe9e2",
      "#ffede7",
      "#fff1ec",
      null,
      "#fff8f6",
      "#fffbff",
      "#ffffff"
    ],
    "error": [
      "#000000",
      null,
      null,
      null,
      "#280001",
      "#2d0001",
      "#310001",
      null,
      null,
      null,
      "#410002",
      null,
      "#490002",
      null,
      null,
      null,
      null,
      "#5c0004",
      null,
      null,
      "#690005",
      null,
      "#710005",
      null,
      "#790006",
      "#7e0007",
      null,
      null,
      null,
      null,
      "#93000a",
      null,
      null,
      null,
      null,
      "#a80710",
      null,
      null,
      null,
      null,
      "#ba1a1a",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#de3730",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#ff5449",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#ff897d",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "#ffb4ab",
      null,
      null,
      null,
      null,
      null,
      null,
      "#ffcfc9",
      null,
      null,
      "#ffdad6",
      null,
      "#ffe2de",
      null,
      "#ffe9e6",
      "#ffedea",
      "#fff0ee",
      null,
      "#fff8f7",
      "#fffbff",
      "#ffffff"
    ]
  },
  "styles": {
    "display": {
      "large": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Regular",
        "fontWeight": 400,
        "fontSize": 57,
        "lineHeight": 64,
        "letterSpacing": -0.25
      },
      "medium": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Regular",
        "fontWeight": 400,
        "fontSize": 45,
        "lineHeight": 52,
        "letterSpacing": 0
      },
      "small": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Regular",
        "fontWeight": 400,
        "fontSize": 36,
        "lineHeight": 44,
        "letterSpacing": 0
      }
    },
    "headline": {
      "large": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Regular",
        "fontWeight": 400,
        "fontSize": 32,
        "lineHeight": 40,
        "letterSpacing": 0
      },
      "medium": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Regular",
        "fontWeight": 400,
        "fontSize": 28,
        "lineHeight": 36,
        "letterSpacing": 0
      },
      "small": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Regular",
        "fontWeight": 400,
        "fontSize": 24,
        "lineHeight": 32,
        "letterSpacing": 0
      }
    },
    "body": {
      "large": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Regular",
        "fontWeight": 400,
        "fontSize": 16,
        "lineHeight": 24,
        "letterSpacing": 0.5
      },
      "medium": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Regular",
        "fontWeight": 400,
        "fontSize": 14,
        "lineHeight": 20,
        "letterSpacing": 0.25
      },
      "small": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Regular",
        "fontWeight": 400,
        "fontSize": 12,
        "lineHeight": 16,
        "letterSpacing": 0.4000000059604645
      }
    },
    "label": {
      "large": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Medium",
        "fontWeight": 500,
        "fontSize": 14,
        "lineHeight": 20,
        "letterSpacing": 0.10000000149011612
      },
      "medium": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Medium",
        "fontWeight": 500,
        "fontSize": 12,
        "lineHeight": 16,
        "letterSpacing": 0.5
      },
      "small": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Medium",
        "fontWeight": 500,
        "fontSize": 11,
        "lineHeight": 16,
        "letterSpacing": 0.5
      }
    },
    "title": {
      "large": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Regular",
        "fontWeight": 400,
        "fontSize": 22,
        "lineHeight": 28,
        "letterSpacing": 0
      },
      "medium": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Medium",
        "fontWeight": 500,
        "fontSize": 16,
        "lineHeight": 24,
        "letterSpacing": 0.15000000596046448
      },
      "small": {
        "fontFamilyName": "Roboto",
        "fontFamilyStyle": "Medium",
        "fontWeight": 500,
        "fontSize": 14,
        "lineHeight": 20,
        "letterSpacing": 0.10000000149011612
      }
    }
  },
  "customColors": []
}